### ISSUE TITLE
Unable to clear library variable set

### ISSUE THREAD

**Issue by worldspawn** [Dalmirog/OctoPosh#312]
In the provided examples a library set is retrieved then Resource.Variables is set to $null. When you try to update this you get an error.

```
Update-OctopusResource : Octopus Server returned an error: Object reference not set to an instance of an object.
Server exception:
Object reference not set to an instance of an object.
System.NullReferenceException
   at Octopus.Server.Web.Api.Actions.VariableSetUpdateAction.OnlyAllowedScopesUsed(VariableSetResource resource, String& message)
   at Octopus.Server.Web.Api.Actions.VariableSetUpdateAction.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
-----------------------
At line:1 char:1
+ Update-OctopusResource -Resource $NewLibraryVariableSet.Resource
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-OctopusResource], OctopusServerException
    + FullyQualifiedErrorId : Octopus.Client.Exceptions.OctopusServerException,Octoposh.Cmdlets.UpdateOctopusResource
```

I am also trying to copy variables from one project to a variable set.

```
$variableSet.resource.variables | where { $_.scope["Environment"] -and $_.scope["Environment"] -eq "Environments-3" } | %{ $NewLibraryVariableSet.Resource.Variables.Add($_) }
```

After running that attempting to update the library set results in:

```
Update-OctopusResource : Octopus Server returned an error: Value cannot be null.
Parameter name: key
Server exception:
Value cannot be null.
Parameter name: key
System.ArgumentNullException
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Octopus.Core.Security.Permissions.AuthorizationRequest..ctor(IEnumerable`1 regardingDocumentIds)
   at Octopus.Server.Permissions.AuthorizationRequestProvider.GetForPermission
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Permissions.PermissionSet.CheckAuthorized(Permission permission, String userId, String[] externalSecurityGroupIds, String[] documentIds)
   at Octopus.Server.Web.Infrastructure.Security.OctopusPrincipal.CheckAuthorizedFor(Permission permission, String[] documentIds)
   at Octopus.Server.Web.Infrastructure.Security.OctopusPrincipal.IsAuthorizedFor(Permission permission, String[] documentIds)
   at Octopus.Server.Web.Infrastructure.Security.VariablePermissions.IsAuthorizedForPermission(Permission permission, IOctopusPrincipalInternal principal,
Boolean isUnscoped, LibraryVariableSet libraryVariableSet, String prj, String env)
   at Octopus.Server.Web.Infrastructure.Security.VariablePermissions.CheckPermissions
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Octopus.Server.Web.Infrastructure.Security.VariablePermissions.<>c__DisplayClass0_0.<StartPermissionCheck>b__4(VariableDeclaration v)
   at Octopus.Server.Web.Api.Actions.VariableSetUpdateAction.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
-----------------------
At line:1 char:1
+ Update-OctopusResource -Resource $NewLibraryVariableSet.Resource
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-OctopusResource], OctopusServerException
```

So I dont seem to be able to do anything to library variable sets.

**Comment by worldspawn** [comment]
I (somehow) had a variable that was referencing an environment that did not exist.
